# Generated by Django 4.2 on 2023-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="tag",
            field=models.ManyToManyField(to="inventory.tag"),
        ),
    ]
