# Generated by Django 4.2 on 2023-04-18 08:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_stock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
