# Generated by Django 4.2 on 2023-04-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="inventory.category",
            ),
        ),
    ]
