# Generated by Django 4.2 on 2023-04-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_brand_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="product_brand",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_brand",
                to="inventory.brand",
            ),
        ),
    ]
